from __future__ import annotations

from sparkspawn.cli import _build_runtime_parser, _run_serve, main
from workspace.cli import (
    DEFAULT_API_BASE_URL,
    DESCRIBE_FLOW_TEXT_EXAMPLE,
    EXIT_GENERAL_FAILURE,
    EXIT_NOT_FOUND,
    EXIT_USAGE_ERROR,
    FLOW_RUN_STDIN_EXAMPLE,
    FLOW_RUN_TEMPFILE_EXAMPLE,
    GET_FLOW_TEXT_EXAMPLE,
    LIST_FLOWS_TEXT_EXAMPLE,
    SPEC_PROPOSAL_CREATE_EXAMPLE,
    SPEC_PROPOSAL_CREATE_STDIN_EXAMPLE,
    SPEC_PROPOSAL_CREATE_TEMPFILE_EXAMPLE,
    _build_workspace_parser,
    _build_error_payload,
    _format_validation_error,
    _handle_response_payload,
    _print_describe_flow_text,
    _print_error_payload,
    _print_success_payload,
    _read_json_input,
    _read_optional_goal,
    _request_json,
    _request_text,
    _response_error_exit_code,
    _run_describe_flow,
    _run_flow_run,
    _run_get_flow,
    _run_list_flows,
    _run_spec_proposal,
    _workspace_agent_url,
    main as workspace_main,
)

__all__ = [
    "DEFAULT_API_BASE_URL",
    "DESCRIBE_FLOW_TEXT_EXAMPLE",
    "EXIT_GENERAL_FAILURE",
    "EXIT_NOT_FOUND",
    "EXIT_USAGE_ERROR",
    "FLOW_RUN_STDIN_EXAMPLE",
    "FLOW_RUN_TEMPFILE_EXAMPLE",
    "GET_FLOW_TEXT_EXAMPLE",
    "LIST_FLOWS_TEXT_EXAMPLE",
    "SPEC_PROPOSAL_CREATE_EXAMPLE",
    "SPEC_PROPOSAL_CREATE_STDIN_EXAMPLE",
    "SPEC_PROPOSAL_CREATE_TEMPFILE_EXAMPLE",
    "_build_error_payload",
    "_build_runtime_parser",
    "_build_workspace_parser",
    "_format_validation_error",
    "_handle_response_payload",
    "_print_describe_flow_text",
    "_print_error_payload",
    "_print_success_payload",
    "_read_json_input",
    "_read_optional_goal",
    "_request_json",
    "_request_text",
    "_response_error_exit_code",
    "_run_describe_flow",
    "_run_flow_run",
    "_run_get_flow",
    "_run_list_flows",
    "_run_serve",
    "_run_spec_proposal",
    "_workspace_agent_url",
    "main",
    "workspace_main",
]
